GET http://localhost:8080/v1/cart/luisito
Accept: application/json

###
POST http://localhost:8080/v1/cart
Content-Type: application/json

{
  "username": "cliente",
  "cartStatus": 1
}

###
