GET http://localhost:8080/v1/user/cliente
Accept: application/json

###
POST http://localhost:8080/v1/user
Content-Type: application/json

{
  "username": "cliente",
  "password": "12345",
  "firstName": "Luis",
  "lastName": "Rodriguez",
  "email": "example@gmail.com",
  "privilege": 1
}

###
POST http://localhost:8080/v1/user
Content-Type: application/json

{
  "username": "repartidor",
  "password": "12345",
  "firstName": "Luis",
  "lastName": "Rodriguez",
  "email": "example@gmail.com",
  "privilege": 2
}